# Generated by Django 4.2.4 on 2023-11-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DominoPizzaApllication',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='DominoPizza',
            new_name='Pizza',
        ),
    ]
