# Generated by Django 4.2.4 on 2023-11-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_rename_dominopizzaapllication_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='не подтвержден', max_length=100),
        ),
    ]
